// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDFsPIXPnyyfdnWYVdyHHCWyVS4llZlNw',
    appId: '1:105163735310:web:7f2f1a44ee3da025c7575f',
    messagingSenderId: '105163735310',
    projectId: 'map-project-kopikanan',
    authDomain: 'map-project-kopikanan.firebaseapp.com',
    storageBucket: 'map-project-kopikanan.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0tsnUnVFCBh_KUDCNmTIoB5Xmc56kF_o',
    appId: '1:105163735310:android:a66dc1ae4a64a308c7575f',
    messagingSenderId: '105163735310',
    projectId: 'map-project-kopikanan',
    storageBucket: 'map-project-kopikanan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbgJ--REQBku6g-ziBobBjzl4QrZfuRyI',
    appId: '1:105163735310:ios:7290d4db505f0604c7575f',
    messagingSenderId: '105163735310',
    projectId: 'map-project-kopikanan',
    storageBucket: 'map-project-kopikanan.firebasestorage.app',
    iosClientId: '105163735310-59phol8clv9eeo058mjtnnka5na9e58p.apps.googleusercontent.com',
    iosBundleId: 'com.example.festquest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbgJ--REQBku6g-ziBobBjzl4QrZfuRyI',
    appId: '1:105163735310:ios:7290d4db505f0604c7575f',
    messagingSenderId: '105163735310',
    projectId: 'map-project-kopikanan',
    storageBucket: 'map-project-kopikanan.firebasestorage.app',
    iosClientId: '105163735310-59phol8clv9eeo058mjtnnka5na9e58p.apps.googleusercontent.com',
    iosBundleId: 'com.example.festquest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDFsPIXPnyyfdnWYVdyHHCWyVS4llZlNw',
    appId: '1:105163735310:web:57a0df889f67b4b9c7575f',
    messagingSenderId: '105163735310',
    projectId: 'map-project-kopikanan',
    authDomain: 'map-project-kopikanan.firebaseapp.com',
    storageBucket: 'map-project-kopikanan.firebasestorage.app',
  );

}